version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  fpm:
    image: 'akeneo/fpm:php-7.2'
    user: 'docker'
    environment:
      COMPOSER_HOME: '/home/docker/.composer'
      PHP_IDE_CONFIG: 'serverName=elasticsearch-training'
      PHP_XDEBUG_ENABLED: 0
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
    working_dir: '/srv/training'
    volumes:
      - './:/srv/training'
      - '~/.composer:/home/docker/.composer'
    networks:
      - 'esnet'

volumes:
  esdata1:
    driver: local

networks:
  esnet:
